name: Deployment Workflow # Automatic deployment workflow

on:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Install dependencies
        run: npm install
        working-directory: personal-webpage-2

      - name: Pre-deployment
        
        run: |
          echo "ACCESS_TOKEN_GH=${{ secrets.ACCESS_TOKEN_GH }}" >> .env.local
          npm run predeploy
        working-directory: personal-webpage-2

      - name: Deploy
        run: |
          git config --global user.email "williamnorland@gmail.com"
          git config --global user.name "William Norland"
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GH }}
        working-directory: personal-webpage-2
